/**
 * Icon definitions for the IconBrowser component
 * Curated list of Material Icons and Font Awesome icons for habit tracking
 */

export interface IconDefinition {
  name: string;
  provider: 'material' | 'fontawesome';
  class: string;
  keywords: string[];
}

// Material Icons - Expanded curated list (~300 icons)
export const MATERIAL_ICONS: IconDefinition[] = [
  // ===== HOME & GENERAL =====
  { name: 'Home', provider: 'material', class: 'Home', keywords: ['home', 'house', 'living'] },
  { name: 'Home Filled', provider: 'material', class: 'HomeFilled', keywords: ['home', 'house'] },
  { name: 'House', provider: 'material', class: 'House', keywords: ['home', 'house', 'building'] },
  { name: 'Cottage', provider: 'material', class: 'Cottage', keywords: ['home', 'house', 'cabin'] },
  { name: 'Apartment', provider: 'material', class: 'Apartment', keywords: ['apartment', 'building', 'home'] },
  { name: 'Star', provider: 'material', class: 'Star', keywords: ['star', 'favorite', 'important', 'rating'] },
  { name: 'Star Border', provider: 'material', class: 'StarBorder', keywords: ['star', 'favorite', 'outline'] },
  { name: 'Star Half', provider: 'material', class: 'StarHalf', keywords: ['star', 'rating', 'half'] },
  { name: 'Favorite', provider: 'material', class: 'Favorite', keywords: ['heart', 'love', 'like', 'favorite'] },
  { name: 'Favorite Border', provider: 'material', class: 'FavoriteBorder', keywords: ['heart', 'love', 'outline'] },
  { name: 'Thumb Up', provider: 'material', class: 'ThumbUp', keywords: ['like', 'approve', 'good', 'thumbs'] },
  { name: 'Thumb Down', provider: 'material', class: 'ThumbDown', keywords: ['dislike', 'bad', 'thumbs'] },
  { name: 'Bookmark', provider: 'material', class: 'Bookmark', keywords: ['bookmark', 'save', 'mark'] },
  { name: 'Bookmark Border', provider: 'material', class: 'BookmarkBorder', keywords: ['bookmark', 'save', 'outline'] },
  { name: 'Label', provider: 'material', class: 'Label', keywords: ['label', 'tag', 'category'] },
  { name: 'Label Important', provider: 'material', class: 'LabelImportant', keywords: ['label', 'important', 'tag'] },

  // ===== CHECK & DONE =====
  { name: 'Check', provider: 'material', class: 'Check', keywords: ['check', 'done', 'complete', 'finished'] },
  { name: 'Check Circle', provider: 'material', class: 'CheckCircle', keywords: ['check', 'done', 'complete', 'success'] },
  { name: 'Check Box', provider: 'material', class: 'CheckBox', keywords: ['checkbox', 'done', 'selected'] },
  { name: 'Done', provider: 'material', class: 'Done', keywords: ['done', 'check', 'complete'] },
  { name: 'Done All', provider: 'material', class: 'DoneAll', keywords: ['done', 'all', 'complete', 'double check'] },
  { name: 'Done Outline', provider: 'material', class: 'DoneOutline', keywords: ['done', 'outline', 'complete'] },
  { name: 'Task Alt', provider: 'material', class: 'TaskAlt', keywords: ['task', 'done', 'complete', 'check'] },
  { name: 'Verified', provider: 'material', class: 'Verified', keywords: ['verified', 'check', 'approved'] },
  { name: 'Verified User', provider: 'material', class: 'VerifiedUser', keywords: ['verified', 'user', 'secure'] },

  // ===== HEALTH & FITNESS =====
  { name: 'Fitness Center', provider: 'material', class: 'FitnessCenter', keywords: ['fitness', 'gym', 'exercise', 'workout', 'weights'] },
  { name: 'Self Improvement', provider: 'material', class: 'SelfImprovement', keywords: ['meditation', 'yoga', 'mindfulness', 'calm', 'zen'] },
  { name: 'Accessibility New', provider: 'material', class: 'AccessibilityNew', keywords: ['body', 'stretch', 'exercise', 'person'] },
  { name: 'Healing', provider: 'material', class: 'Healing', keywords: ['health', 'medical', 'recovery', 'bandage'] },
  { name: 'Bedtime', provider: 'material', class: 'Bedtime', keywords: ['sleep', 'rest', 'night', 'moon'] },
  { name: 'Hotel', provider: 'material', class: 'Hotel', keywords: ['sleep', 'bed', 'rest', 'night'] },
  { name: 'King Bed', provider: 'material', class: 'KingBed', keywords: ['bed', 'sleep', 'rest'] },
  { name: 'Single Bed', provider: 'material', class: 'SingleBed', keywords: ['bed', 'sleep', 'rest'] },
  { name: 'Spa', provider: 'material', class: 'Spa', keywords: ['spa', 'relax', 'wellness', 'flower'] },
  { name: 'Pool', provider: 'material', class: 'Pool', keywords: ['swim', 'pool', 'water', 'exercise'] },
  { name: 'Hiking', provider: 'material', class: 'Hiking', keywords: ['hiking', 'walk', 'outdoor', 'nature', 'mountain'] },
  { name: 'Directions Run', provider: 'material', class: 'DirectionsRun', keywords: ['run', 'running', 'exercise', 'jog'] },
  { name: 'Directions Walk', provider: 'material', class: 'DirectionsWalk', keywords: ['walk', 'walking', 'steps'] },
  { name: 'Directions Bike', provider: 'material', class: 'DirectionsBike', keywords: ['bike', 'cycling', 'exercise'] },
  { name: 'Monitor Heart', provider: 'material', class: 'MonitorHeart', keywords: ['heart', 'health', 'monitor', 'pulse'] },
  { name: 'Medication', provider: 'material', class: 'Medication', keywords: ['medicine', 'pill', 'health', 'drug'] },
  { name: 'Medical Services', provider: 'material', class: 'MedicalServices', keywords: ['medical', 'health', 'doctor', 'first aid'] },
  { name: 'Local Hospital', provider: 'material', class: 'LocalHospital', keywords: ['hospital', 'health', 'medical'] },
  { name: 'Psychology', provider: 'material', class: 'Psychology', keywords: ['brain', 'mind', 'mental', 'think', 'psychology'] },
  { name: 'Mood', provider: 'material', class: 'Mood', keywords: ['mood', 'happy', 'smile', 'emotion'] },
  { name: 'Mood Bad', provider: 'material', class: 'MoodBad', keywords: ['mood', 'sad', 'unhappy', 'emotion'] },
  { name: 'Sentiment Satisfied', provider: 'material', class: 'SentimentSatisfied', keywords: ['happy', 'satisfied', 'smile'] },
  { name: 'Sentiment Very Satisfied', provider: 'material', class: 'SentimentVerySatisfied', keywords: ['very happy', 'excited', 'joy'] },
  { name: 'Sentiment Dissatisfied', provider: 'material', class: 'SentimentDissatisfied', keywords: ['sad', 'unhappy', 'frown'] },
  { name: 'Sentiment Neutral', provider: 'material', class: 'SentimentNeutral', keywords: ['neutral', 'meh', 'okay'] },

  // ===== LEARNING & EDUCATION =====
  { name: 'Menu Book', provider: 'material', class: 'MenuBook', keywords: ['book', 'read', 'study', 'learn', 'library'] },
  { name: 'Auto Stories', provider: 'material', class: 'AutoStories', keywords: ['book', 'read', 'story', 'pages'] },
  { name: 'Import Contacts', provider: 'material', class: 'ImportContacts', keywords: ['book', 'open', 'read'] },
  { name: 'Chrome Reader', provider: 'material', class: 'ChromeReaderMode', keywords: ['read', 'article', 'text'] },
  { name: 'School', provider: 'material', class: 'School', keywords: ['school', 'education', 'graduate', 'learn', 'cap'] },
  { name: 'History Edu', provider: 'material', class: 'HistoryEdu', keywords: ['education', 'history', 'writing', 'quill'] },
  { name: 'Science', provider: 'material', class: 'Science', keywords: ['science', 'lab', 'experiment', 'flask'] },
  { name: 'Biotech', provider: 'material', class: 'Biotech', keywords: ['biotech', 'science', 'dna', 'biology'] },
  { name: 'Architecture', provider: 'material', class: 'Architecture', keywords: ['architecture', 'design', 'compass'] },
  { name: 'Calculate', provider: 'material', class: 'Calculate', keywords: ['math', 'calculate', 'numbers'] },
  { name: 'Functions', provider: 'material', class: 'Functions', keywords: ['math', 'function', 'formula'] },
  { name: 'Translate', provider: 'material', class: 'Translate', keywords: ['translate', 'language', 'learn'] },
  { name: 'Abc', provider: 'material', class: 'Abc', keywords: ['abc', 'alphabet', 'letters', 'language'] },

  // ===== WORK & PRODUCTIVITY =====
  { name: 'Work', provider: 'material', class: 'Work', keywords: ['work', 'job', 'briefcase', 'business'] },
  { name: 'Work Outline', provider: 'material', class: 'WorkOutline', keywords: ['work', 'job', 'briefcase'] },
  { name: 'Business Center', provider: 'material', class: 'BusinessCenter', keywords: ['business', 'work', 'briefcase'] },
  { name: 'Laptop Mac', provider: 'material', class: 'LaptopMac', keywords: ['laptop', 'computer', 'work', 'tech'] },
  { name: 'Computer', provider: 'material', class: 'Computer', keywords: ['computer', 'desktop', 'work'] },
  { name: 'Devices', provider: 'material', class: 'Devices', keywords: ['devices', 'tech', 'phone', 'tablet'] },
  { name: 'Phone Iphone', provider: 'material', class: 'PhoneIphone', keywords: ['phone', 'mobile', 'iphone'] },
  { name: 'Tablet Mac', provider: 'material', class: 'TabletMac', keywords: ['tablet', 'ipad', 'device'] },
  { name: 'Watch', provider: 'material', class: 'Watch', keywords: ['watch', 'time', 'wearable'] },
  { name: 'Headphones', provider: 'material', class: 'Headphones', keywords: ['headphones', 'audio', 'music', 'listen'] },
  { name: 'Lightbulb', provider: 'material', class: 'Lightbulb', keywords: ['idea', 'lightbulb', 'creative', 'innovation'] },
  { name: 'Tips And Updates', provider: 'material', class: 'TipsAndUpdates', keywords: ['tips', 'idea', 'lightbulb', 'suggestion'] },
  { name: 'Create', provider: 'material', class: 'Create', keywords: ['create', 'write', 'edit', 'pencil'] },
  { name: 'Edit', provider: 'material', class: 'Edit', keywords: ['edit', 'pencil', 'write', 'modify'] },
  { name: 'Edit Note', provider: 'material', class: 'EditNote', keywords: ['edit', 'note', 'write'] },
  { name: 'Note', provider: 'material', class: 'Note', keywords: ['note', 'paper', 'document'] },
  { name: 'Note Add', provider: 'material', class: 'NoteAdd', keywords: ['note', 'add', 'new', 'create'] },
  { name: 'Sticky Note', provider: 'material', class: 'StickyNote2', keywords: ['sticky', 'note', 'post-it'] },
  { name: 'Article', provider: 'material', class: 'Article', keywords: ['article', 'blog', 'write', 'document', 'news'] },
  { name: 'Description', provider: 'material', class: 'Description', keywords: ['document', 'file', 'description'] },
  { name: 'Assignment', provider: 'material', class: 'Assignment', keywords: ['assignment', 'task', 'clipboard'] },
  { name: 'Assignment Turned In', provider: 'material', class: 'AssignmentTurnedIn', keywords: ['assignment', 'done', 'complete'] },
  { name: 'Pending Actions', provider: 'material', class: 'PendingActions', keywords: ['pending', 'waiting', 'clock'] },
  { name: 'Rule', provider: 'material', class: 'Rule', keywords: ['rule', 'check', 'verify'] },
  { name: 'Checklist', provider: 'material', class: 'Checklist', keywords: ['checklist', 'todo', 'tasks', 'list'] },
  { name: 'Playlist Add Check', provider: 'material', class: 'PlaylistAddCheck', keywords: ['playlist', 'done', 'complete'] },
  { name: 'Fact Check', provider: 'material', class: 'FactCheck', keywords: ['fact', 'check', 'verify', 'list'] },

  // ===== CODE & DEVELOPMENT =====
  { name: 'Code', provider: 'material', class: 'Code', keywords: ['code', 'programming', 'dev', 'developer', 'brackets'] },
  { name: 'Code Off', provider: 'material', class: 'CodeOff', keywords: ['code', 'off', 'no code'] },
  { name: 'Terminal', provider: 'material', class: 'Terminal', keywords: ['terminal', 'command', 'console', 'cli'] },
  { name: 'Data Object', provider: 'material', class: 'DataObject', keywords: ['data', 'json', 'object', 'code'] },
  { name: 'Data Array', provider: 'material', class: 'DataArray', keywords: ['data', 'array', 'code', 'brackets'] },
  { name: 'Integration Instructions', provider: 'material', class: 'IntegrationInstructions', keywords: ['integration', 'api', 'code'] },
  { name: 'Bug Report', provider: 'material', class: 'BugReport', keywords: ['bug', 'report', 'error', 'debug'] },
  { name: 'Build', provider: 'material', class: 'Build', keywords: ['build', 'tools', 'wrench', 'settings'] },
  { name: 'Build Circle', provider: 'material', class: 'BuildCircle', keywords: ['build', 'tools', 'wrench'] },
  { name: 'Construction', provider: 'material', class: 'Construction', keywords: ['construction', 'tools', 'work'] },
  { name: 'Engineering', provider: 'material', class: 'Engineering', keywords: ['engineering', 'gear', 'technical'] },
  { name: 'Handyman', provider: 'material', class: 'Handyman', keywords: ['handyman', 'tools', 'repair'] },
  { name: 'Memory', provider: 'material', class: 'Memory', keywords: ['memory', 'chip', 'hardware', 'ram'] },
  { name: 'Storage', provider: 'material', class: 'Storage', keywords: ['storage', 'database', 'data'] },
  { name: 'Cloud', provider: 'material', class: 'Cloud', keywords: ['cloud', 'storage', 'upload'] },
  { name: 'Cloud Upload', provider: 'material', class: 'CloudUpload', keywords: ['cloud', 'upload', 'backup'] },
  { name: 'Cloud Download', provider: 'material', class: 'CloudDownload', keywords: ['cloud', 'download'] },
  { name: 'Cloud Done', provider: 'material', class: 'CloudDone', keywords: ['cloud', 'done', 'synced'] },
  { name: 'Cloud Sync', provider: 'material', class: 'CloudSync', keywords: ['cloud', 'sync', 'refresh'] },

  // ===== FINANCE & MONEY =====
  { name: 'Attach Money', provider: 'material', class: 'AttachMoney', keywords: ['money', 'finance', 'dollar', 'savings'] },
  { name: 'Money Off', provider: 'material', class: 'MoneyOff', keywords: ['money', 'off', 'discount', 'free'] },
  { name: 'Savings', provider: 'material', class: 'Savings', keywords: ['savings', 'piggy', 'bank', 'money'] },
  { name: 'Account Balance', provider: 'material', class: 'AccountBalance', keywords: ['bank', 'finance', 'money', 'building'] },
  { name: 'Account Balance Wallet', provider: 'material', class: 'AccountBalanceWallet', keywords: ['wallet', 'money', 'payment'] },
  { name: 'Paid', provider: 'material', class: 'Paid', keywords: ['paid', 'money', 'payment', 'check'] },
  { name: 'Payment', provider: 'material', class: 'Payment', keywords: ['payment', 'card', 'credit'] },
  { name: 'Credit Card', provider: 'material', class: 'CreditCard', keywords: ['credit', 'card', 'payment'] },
  { name: 'Receipt', provider: 'material', class: 'Receipt', keywords: ['receipt', 'bill', 'purchase'] },
  { name: 'Receipt Long', provider: 'material', class: 'ReceiptLong', keywords: ['receipt', 'bill', 'long'] },
  { name: 'Redeem', provider: 'material', class: 'Redeem', keywords: ['redeem', 'gift', 'reward'] },
  { name: 'Point Of Sale', provider: 'material', class: 'PointOfSale', keywords: ['pos', 'sale', 'payment'] },
  { name: 'Currency Exchange', provider: 'material', class: 'CurrencyExchange', keywords: ['currency', 'exchange', 'money'] },
  { name: 'Monetization On', provider: 'material', class: 'MonetizationOn', keywords: ['money', 'coin', 'dollar'] },

  // ===== TIME & CALENDAR =====
  { name: 'Calendar Month', provider: 'material', class: 'CalendarMonth', keywords: ['calendar', 'date', 'schedule', 'plan', 'month'] },
  { name: 'Calendar Today', provider: 'material', class: 'CalendarToday', keywords: ['calendar', 'today', 'date'] },
  { name: 'Date Range', provider: 'material', class: 'DateRange', keywords: ['date', 'range', 'calendar'] },
  { name: 'Event', provider: 'material', class: 'Event', keywords: ['event', 'calendar', 'date', 'schedule'] },
  { name: 'Event Available', provider: 'material', class: 'EventAvailable', keywords: ['event', 'available', 'check'] },
  { name: 'Event Busy', provider: 'material', class: 'EventBusy', keywords: ['event', 'busy', 'cancel'] },
  { name: 'Event Note', provider: 'material', class: 'EventNote', keywords: ['event', 'note', 'calendar'] },
  { name: 'Event Repeat', provider: 'material', class: 'EventRepeat', keywords: ['event', 'repeat', 'recurring'] },
  { name: 'Today', provider: 'material', class: 'Today', keywords: ['today', 'calendar', 'date'] },
  { name: 'Schedule', provider: 'material', class: 'Schedule', keywords: ['schedule', 'clock', 'time'] },
  { name: 'Access Time', provider: 'material', class: 'AccessTime', keywords: ['time', 'clock', 'access'] },
  { name: 'Timer', provider: 'material', class: 'Timer', keywords: ['timer', 'clock', 'time', 'stopwatch'] },
  { name: 'Timer Off', provider: 'material', class: 'TimerOff', keywords: ['timer', 'off', 'stop'] },
  { name: 'Timelapse', provider: 'material', class: 'Timelapse', keywords: ['timelapse', 'time', 'clock'] },
  { name: 'Alarm', provider: 'material', class: 'Alarm', keywords: ['alarm', 'wake', 'time', 'reminder'] },
  { name: 'Alarm On', provider: 'material', class: 'AlarmOn', keywords: ['alarm', 'on', 'active'] },
  { name: 'Alarm Off', provider: 'material', class: 'AlarmOff', keywords: ['alarm', 'off', 'disabled'] },
  { name: 'Alarm Add', provider: 'material', class: 'AlarmAdd', keywords: ['alarm', 'add', 'new'] },
  { name: 'Hourglass Empty', provider: 'material', class: 'HourglassEmpty', keywords: ['hourglass', 'time', 'wait'] },
  { name: 'Hourglass Full', provider: 'material', class: 'HourglassFull', keywords: ['hourglass', 'time', 'full'] },
  { name: 'Update', provider: 'material', class: 'Update', keywords: ['update', 'refresh', 'time'] },
  { name: 'History', provider: 'material', class: 'History', keywords: ['history', 'past', 'time'] },
  { name: 'Restore', provider: 'material', class: 'Restore', keywords: ['restore', 'undo', 'history'] },

  // ===== GOALS & ACHIEVEMENT =====
  { name: 'Track Changes', provider: 'material', class: 'TrackChanges', keywords: ['target', 'goal', 'aim', 'focus', 'crosshair'] },
  { name: 'Gps Fixed', provider: 'material', class: 'GpsFixed', keywords: ['gps', 'target', 'location', 'focus'] },
  { name: 'Flag', provider: 'material', class: 'Flag', keywords: ['flag', 'milestone', 'goal', 'mark'] },
  { name: 'Flag Circle', provider: 'material', class: 'FlagCircle', keywords: ['flag', 'circle', 'goal'] },
  { name: 'Outlined Flag', provider: 'material', class: 'OutlinedFlag', keywords: ['flag', 'outline', 'goal'] },
  { name: 'Tour', provider: 'material', class: 'Tour', keywords: ['tour', 'flag', 'destination'] },
  { name: 'Trending Up', provider: 'material', class: 'TrendingUp', keywords: ['trending', 'growth', 'progress', 'up', 'increase'] },
  { name: 'Trending Down', provider: 'material', class: 'TrendingDown', keywords: ['trending', 'down', 'decrease'] },
  { name: 'Trending Flat', provider: 'material', class: 'TrendingFlat', keywords: ['trending', 'flat', 'stable'] },
  { name: 'Leaderboard', provider: 'material', class: 'Leaderboard', keywords: ['leaderboard', 'ranking', 'score', 'chart'] },
  { name: 'Emoji Events', provider: 'material', class: 'EmojiEvents', keywords: ['trophy', 'award', 'win', 'achievement', 'cup'] },
  { name: 'Military Tech', provider: 'material', class: 'MilitaryTech', keywords: ['medal', 'award', 'achievement', 'badge'] },
  { name: 'Workspace Premium', provider: 'material', class: 'WorkspacePremium', keywords: ['premium', 'badge', 'award'] },
  { name: 'Grade', provider: 'material', class: 'Grade', keywords: ['grade', 'star', 'rating'] },
  { name: 'Stars', provider: 'material', class: 'Stars', keywords: ['stars', 'special', 'featured'] },
  { name: 'Auto Awesome', provider: 'material', class: 'AutoAwesome', keywords: ['awesome', 'magic', 'sparkle', 'ai'] },

  // ===== SOCIAL & PEOPLE =====
  { name: 'Person', provider: 'material', class: 'Person', keywords: ['person', 'user', 'profile', 'individual'] },
  { name: 'Person Outline', provider: 'material', class: 'PersonOutline', keywords: ['person', 'user', 'outline'] },
  { name: 'Person Add', provider: 'material', class: 'PersonAdd', keywords: ['person', 'add', 'new user'] },
  { name: 'Person Remove', provider: 'material', class: 'PersonRemove', keywords: ['person', 'remove', 'delete'] },
  { name: 'Group', provider: 'material', class: 'Group', keywords: ['group', 'team', 'people', 'community'] },
  { name: 'Groups', provider: 'material', class: 'Groups', keywords: ['groups', 'team', 'people', 'community'] },
  { name: 'Group Add', provider: 'material', class: 'GroupAdd', keywords: ['group', 'add', 'team'] },
  { name: 'People', provider: 'material', class: 'People', keywords: ['people', 'group', 'team'] },
  { name: 'Family Restroom', provider: 'material', class: 'FamilyRestroom', keywords: ['family', 'people', 'home', 'parents'] },
  { name: 'Diversity', provider: 'material', class: 'Diversity3', keywords: ['diversity', 'group', 'team', 'inclusive'] },
  { name: 'Elderly', provider: 'material', class: 'Elderly', keywords: ['elderly', 'senior', 'old'] },
  { name: 'Face', provider: 'material', class: 'Face', keywords: ['face', 'person', 'profile'] },
  { name: 'Face Retouching', provider: 'material', class: 'FaceRetouchingNatural', keywords: ['face', 'beauty', 'natural'] },
  { name: 'Emoji People', provider: 'material', class: 'EmojiPeople', keywords: ['emoji', 'people', 'wave', 'hello'] },
  { name: 'Record Voice', provider: 'material', class: 'RecordVoiceOver', keywords: ['voice', 'speak', 'talk', 'record'] },
  { name: 'Connect Without Contact', provider: 'material', class: 'ConnectWithoutContact', keywords: ['connect', 'social', 'network'] },
  { name: 'Handshake', provider: 'material', class: 'Handshake', keywords: ['handshake', 'deal', 'agreement', 'partnership'] },
  { name: 'Waving Hand', provider: 'material', class: 'WavingHand', keywords: ['wave', 'hello', 'greeting'] },

  // ===== COMMUNICATION =====
  { name: 'Chat', provider: 'material', class: 'Chat', keywords: ['chat', 'message', 'talk', 'communication'] },
  { name: 'Chat Bubble', provider: 'material', class: 'ChatBubble', keywords: ['chat', 'bubble', 'message'] },
  { name: 'Forum', provider: 'material', class: 'Forum', keywords: ['forum', 'discussion', 'chat'] },
  { name: 'Question Answer', provider: 'material', class: 'QuestionAnswer', keywords: ['question', 'answer', 'faq', 'chat'] },
  { name: 'Comment', provider: 'material', class: 'Comment', keywords: ['comment', 'note', 'feedback'] },
  { name: 'Feedback', provider: 'material', class: 'Feedback', keywords: ['feedback', 'comment', 'review'] },
  { name: 'Email', provider: 'material', class: 'Email', keywords: ['email', 'mail', 'message', 'envelope'] },
  { name: 'Mail', provider: 'material', class: 'Mail', keywords: ['mail', 'email', 'message'] },
  { name: 'Mail Outline', provider: 'material', class: 'MailOutline', keywords: ['mail', 'email', 'outline'] },
  { name: 'Send', provider: 'material', class: 'Send', keywords: ['send', 'message', 'paper plane'] },
  { name: 'Phone', provider: 'material', class: 'Phone', keywords: ['phone', 'call', 'contact'] },
  { name: 'Call', provider: 'material', class: 'Call', keywords: ['call', 'phone', 'contact'] },
  { name: 'Video Call', provider: 'material', class: 'VideoCall', keywords: ['video', 'call', 'meeting'] },
  { name: 'Videocam', provider: 'material', class: 'Videocam', keywords: ['video', 'camera', 'record'] },
  { name: 'Notifications', provider: 'material', class: 'Notifications', keywords: ['notifications', 'bell', 'alert'] },
  { name: 'Notifications Active', provider: 'material', class: 'NotificationsActive', keywords: ['notifications', 'active', 'ringing'] },
  { name: 'Notifications Off', provider: 'material', class: 'NotificationsOff', keywords: ['notifications', 'off', 'silent'] },
  { name: 'Campaign', provider: 'material', class: 'Campaign', keywords: ['campaign', 'announce', 'megaphone'] },
  { name: 'Announcement', provider: 'material', class: 'Announcement', keywords: ['announcement', 'news', 'important'] },

  // ===== ENTERTAINMENT & HOBBIES =====
  { name: 'Music Note', provider: 'material', class: 'MusicNote', keywords: ['music', 'note', 'audio', 'sound'] },
  { name: 'Music Off', provider: 'material', class: 'MusicOff', keywords: ['music', 'off', 'mute'] },
  { name: 'Queue Music', provider: 'material', class: 'QueueMusic', keywords: ['music', 'queue', 'playlist'] },
  { name: 'Library Music', provider: 'material', class: 'LibraryMusic', keywords: ['music', 'library', 'collection'] },
  { name: 'Audio Track', provider: 'material', class: 'Audiotrack', keywords: ['audio', 'track', 'music'] },
  { name: 'Piano', provider: 'material', class: 'Piano', keywords: ['piano', 'music', 'instrument', 'keys'] },
  { name: 'Mic', provider: 'material', class: 'Mic', keywords: ['mic', 'microphone', 'record', 'voice'] },
  { name: 'Camera Alt', provider: 'material', class: 'CameraAlt', keywords: ['camera', 'photo', 'picture', 'photography'] },
  { name: 'Photo Camera', provider: 'material', class: 'PhotoCamera', keywords: ['camera', 'photo', 'picture'] },
  { name: 'Palette', provider: 'material', class: 'Palette', keywords: ['art', 'paint', 'creative', 'design', 'color'] },
  { name: 'Brush', provider: 'material', class: 'Brush', keywords: ['paint', 'art', 'brush', 'creative'] },
  { name: 'Draw', provider: 'material', class: 'Draw', keywords: ['draw', 'pencil', 'art', 'design'] },
  { name: 'Gesture', provider: 'material', class: 'Gesture', keywords: ['gesture', 'draw', 'signature'] },
  { name: 'Color Lens', provider: 'material', class: 'ColorLens', keywords: ['color', 'lens', 'palette'] },
  { name: 'Sports Soccer', provider: 'material', class: 'SportsSoccer', keywords: ['soccer', 'sports', 'football', 'ball'] },
  { name: 'Sports Basketball', provider: 'material', class: 'SportsBasketball', keywords: ['basketball', 'sports', 'ball'] },
  { name: 'Sports Football', provider: 'material', class: 'SportsFootball', keywords: ['football', 'sports', 'american'] },
  { name: 'Sports Baseball', provider: 'material', class: 'SportsBaseball', keywords: ['baseball', 'sports', 'ball'] },
  { name: 'Sports Tennis', provider: 'material', class: 'SportsTennis', keywords: ['tennis', 'sports', 'racket'] },
  { name: 'Sports Golf', provider: 'material', class: 'SportsGolf', keywords: ['golf', 'sports'] },
  { name: 'Sports Volleyball', provider: 'material', class: 'SportsVolleyball', keywords: ['volleyball', 'sports'] },
  { name: 'Sports Hockey', provider: 'material', class: 'SportsHockey', keywords: ['hockey', 'sports', 'ice'] },
  { name: 'Sports Martial Arts', provider: 'material', class: 'SportsMartialArts', keywords: ['martial arts', 'karate', 'sports'] },
  { name: 'Sports Kabaddi', provider: 'material', class: 'SportsKabaddi', keywords: ['kabaddi', 'wrestling', 'sports'] },
  { name: 'Sports Esports', provider: 'material', class: 'SportsEsports', keywords: ['game', 'gaming', 'controller', 'esports'] },
  { name: 'Skateboarding', provider: 'material', class: 'Skateboarding', keywords: ['skateboard', 'sports', 'extreme'] },
  { name: 'Surfing', provider: 'material', class: 'Surfing', keywords: ['surfing', 'water', 'sports', 'beach'] },
  { name: 'Kayaking', provider: 'material', class: 'Kayaking', keywords: ['kayak', 'water', 'sports'] },
  { name: 'Snowboarding', provider: 'material', class: 'Snowboarding', keywords: ['snowboard', 'winter', 'sports'] },
  { name: 'Sledding', provider: 'material', class: 'Sledding', keywords: ['sled', 'winter', 'snow'] },
  { name: 'Downhill Skiing', provider: 'material', class: 'DownhillSkiing', keywords: ['skiing', 'winter', 'sports'] },
  { name: 'Paragliding', provider: 'material', class: 'Paragliding', keywords: ['paragliding', 'flying', 'extreme'] },
  { name: 'Kitesurfing', provider: 'material', class: 'Kitesurfing', keywords: ['kitesurfing', 'water', 'sports'] },
  { name: 'Scuba Diving', provider: 'material', class: 'ScubaDiving', keywords: ['diving', 'water', 'ocean'] },
  { name: 'Pets', provider: 'material', class: 'Pets', keywords: ['pets', 'animal', 'dog', 'cat', 'paw'] },
  { name: 'Cruelty Free', provider: 'material', class: 'CrueltyFree', keywords: ['bunny', 'rabbit', 'animal', 'pet'] },
  { name: 'Smart Toy', provider: 'material', class: 'SmartToy', keywords: ['toy', 'robot', 'game', 'play'] },
  { name: 'Toys', provider: 'material', class: 'Toys', keywords: ['toys', 'play', 'game', 'kids'] },
  { name: 'Interests', provider: 'material', class: 'Interests', keywords: ['interests', 'hobby', 'star', 'heart'] },
  { name: 'Theater Comedy', provider: 'material', class: 'TheaterComedy', keywords: ['theater', 'drama', 'comedy', 'masks'] },
  { name: 'Movie', provider: 'material', class: 'Movie', keywords: ['movie', 'film', 'video', 'cinema'] },
  { name: 'TV', provider: 'material', class: 'Tv', keywords: ['tv', 'television', 'watch', 'screen'] },
  { name: 'Podcasts', provider: 'material', class: 'Podcasts', keywords: ['podcast', 'audio', 'listen'] },

  // ===== FOOD & DRINK =====
  { name: 'Restaurant', provider: 'material', class: 'Restaurant', keywords: ['food', 'restaurant', 'eat', 'dining', 'utensils'] },
  { name: 'Restaurant Menu', provider: 'material', class: 'RestaurantMenu', keywords: ['menu', 'food', 'restaurant'] },
  { name: 'Dining', provider: 'material', class: 'Dining', keywords: ['dining', 'food', 'eat'] },
  { name: 'Local Cafe', provider: 'material', class: 'LocalCafe', keywords: ['coffee', 'cafe', 'drink', 'morning'] },
  { name: 'Coffee', provider: 'material', class: 'Coffee', keywords: ['coffee', 'drink', 'cafe', 'cup'] },
  { name: 'Coffee Maker', provider: 'material', class: 'CoffeeMaker', keywords: ['coffee', 'maker', 'machine'] },
  { name: 'Free Breakfast', provider: 'material', class: 'FreeBreakfast', keywords: ['breakfast', 'coffee', 'morning'] },
  { name: 'Water Drop', provider: 'material', class: 'WaterDrop', keywords: ['water', 'drink', 'hydration', 'drop'] },
  { name: 'Opacity', provider: 'material', class: 'Opacity', keywords: ['water', 'drop', 'opacity'] },
  { name: 'Local Bar', provider: 'material', class: 'LocalBar', keywords: ['bar', 'drink', 'cocktail', 'alcohol'] },
  { name: 'Wine Bar', provider: 'material', class: 'WineBar', keywords: ['wine', 'drink', 'alcohol'] },
  { name: 'Liquor', provider: 'material', class: 'Liquor', keywords: ['liquor', 'drink', 'alcohol', 'bottle'] },
  { name: 'No Drinks', provider: 'material', class: 'NoDrinks', keywords: ['no drinks', 'sober', 'no alcohol'] },
  { name: 'Apple', provider: 'material', class: 'Apple', keywords: ['apple', 'fruit', 'healthy', 'nutrition'] },
  { name: 'Egg', provider: 'material', class: 'Egg', keywords: ['egg', 'food', 'breakfast'] },
  { name: 'Egg Alt', provider: 'material', class: 'EggAlt', keywords: ['egg', 'food', 'fried'] },
  { name: 'Rice Bowl', provider: 'material', class: 'RiceBowl', keywords: ['rice', 'food', 'bowl', 'asian'] },
  { name: 'Ramen Dining', provider: 'material', class: 'RamenDining', keywords: ['ramen', 'noodles', 'food', 'asian'] },
  { name: 'Lunch Dining', provider: 'material', class: 'LunchDining', keywords: ['lunch', 'food', 'meal'] },
  { name: 'Bakery Dining', provider: 'material', class: 'BakeryDining', keywords: ['bakery', 'bread', 'food'] },
  { name: 'Cake', provider: 'material', class: 'Cake', keywords: ['cake', 'dessert', 'birthday', 'sweet'] },
  { name: 'Icecream', provider: 'material', class: 'Icecream', keywords: ['icecream', 'dessert', 'sweet', 'cold'] },
  { name: 'Kitchen', provider: 'material', class: 'Kitchen', keywords: ['cook', 'kitchen', 'food', 'meal'] },
  { name: 'Outdoor Grill', provider: 'material', class: 'OutdoorGrill', keywords: ['grill', 'bbq', 'cooking', 'outdoor'] },
  { name: 'Blender', provider: 'material', class: 'Blender', keywords: ['blender', 'smoothie', 'kitchen'] },

  // ===== SHOPPING & COMMERCE =====
  { name: 'Shopping Cart', provider: 'material', class: 'ShoppingCart', keywords: ['shopping', 'cart', 'buy', 'store', 'ecommerce'] },
  { name: 'Add Shopping Cart', provider: 'material', class: 'AddShoppingCart', keywords: ['shopping', 'cart', 'add'] },
  { name: 'Remove Shopping Cart', provider: 'material', class: 'RemoveShoppingCart', keywords: ['shopping', 'cart', 'remove'] },
  { name: 'Shopping Bag', provider: 'material', class: 'ShoppingBag', keywords: ['shopping', 'bag', 'buy'] },
  { name: 'Shopping Basket', provider: 'material', class: 'ShoppingBasket', keywords: ['shopping', 'basket', 'buy'] },
  { name: 'Store', provider: 'material', class: 'Store', keywords: ['store', 'shop', 'building'] },
  { name: 'Storefront', provider: 'material', class: 'Storefront', keywords: ['store', 'shop', 'front'] },
  { name: 'Local Mall', provider: 'material', class: 'LocalMall', keywords: ['mall', 'shopping', 'store'] },
  { name: 'Sell', provider: 'material', class: 'Sell', keywords: ['sell', 'tag', 'price'] },
  { name: 'Discount', provider: 'material', class: 'Discount', keywords: ['discount', 'sale', 'percent'] },
  { name: 'Local Offer', provider: 'material', class: 'LocalOffer', keywords: ['offer', 'tag', 'label', 'sale'] },
  { name: 'Loyalty', provider: 'material', class: 'Loyalty', keywords: ['loyalty', 'reward', 'heart'] },
  { name: 'Card Giftcard', provider: 'material', class: 'CardGiftcard', keywords: ['gift', 'card', 'present'] },

  // ===== CLEANING & HOME =====
  { name: 'Cleaning Services', provider: 'material', class: 'CleaningServices', keywords: ['clean', 'cleaning', 'tidy', 'spray'] },
  { name: 'Dry Cleaning', provider: 'material', class: 'DryCleaning', keywords: ['laundry', 'cleaning', 'dry'] },
  { name: 'Local Laundry Service', provider: 'material', class: 'LocalLaundryService', keywords: ['laundry', 'cleaning', 'wash'] },
  { name: 'Checkroom', provider: 'material', class: 'Checkroom', keywords: ['coat', 'hanger', 'clothes'] },
  { name: 'Iron', provider: 'material', class: 'Iron', keywords: ['iron', 'clothes', 'laundry'] },
  { name: 'Bathroom', provider: 'material', class: 'Bathroom', keywords: ['bathroom', 'bath', 'shower'] },
  { name: 'Bathtub', provider: 'material', class: 'Bathtub', keywords: ['bathtub', 'bath', 'relax'] },
  { name: 'Shower', provider: 'material', class: 'Shower', keywords: ['shower', 'bath', 'water'] },
  { name: 'Soap', provider: 'material', class: 'Soap', keywords: ['soap', 'clean', 'wash'] },
  { name: 'Sanitizer', provider: 'material', class: 'Sanitizer', keywords: ['sanitizer', 'clean', 'hygiene'] },
  { name: 'Weekend', provider: 'material', class: 'Weekend', keywords: ['couch', 'sofa', 'weekend', 'relax'] },
  { name: 'Chair', provider: 'material', class: 'Chair', keywords: ['chair', 'sit', 'furniture'] },
  { name: 'Table Bar', provider: 'material', class: 'TableBar', keywords: ['table', 'furniture', 'bar'] },
  { name: 'Deck', provider: 'material', class: 'Deck', keywords: ['deck', 'outdoor', 'patio'] },
  { name: 'Yard', provider: 'material', class: 'Yard', keywords: ['yard', 'garden', 'outdoor'] },
  { name: 'Fence', provider: 'material', class: 'Fence', keywords: ['fence', 'yard', 'boundary'] },
  { name: 'Grass', provider: 'material', class: 'Grass', keywords: ['grass', 'lawn', 'garden'] },

  // ===== NATURE & ENVIRONMENT =====
  { name: 'Nature', provider: 'material', class: 'Nature', keywords: ['nature', 'tree', 'plant', 'environment'] },
  { name: 'Nature People', provider: 'material', class: 'NaturePeople', keywords: ['nature', 'people', 'outdoor'] },
  { name: 'Park', provider: 'material', class: 'Park', keywords: ['park', 'tree', 'outdoor', 'nature'] },
  { name: 'Forest', provider: 'material', class: 'Forest', keywords: ['forest', 'trees', 'nature'] },
  { name: 'Eco', provider: 'material', class: 'Eco', keywords: ['eco', 'leaf', 'green', 'environment', 'sustainable'] },
  { name: 'Yard', provider: 'material', class: 'Yard', keywords: ['yard', 'garden', 'plant'] },
  { name: 'Compost', provider: 'material', class: 'Compost', keywords: ['compost', 'recycle', 'green'] },
  { name: 'Recycling', provider: 'material', class: 'Recycling', keywords: ['recycle', 'green', 'environment'] },
  { name: 'Delete Sweep', provider: 'material', class: 'DeleteSweep', keywords: ['delete', 'sweep', 'clean'] },
  { name: 'Terrain', provider: 'material', class: 'Terrain', keywords: ['terrain', 'mountain', 'landscape'] },
  { name: 'Landscape', provider: 'material', class: 'Landscape', keywords: ['landscape', 'mountain', 'nature'] },
  { name: 'Water', provider: 'material', class: 'Water', keywords: ['water', 'wave', 'ocean'] },
  { name: 'Waves', provider: 'material', class: 'Waves', keywords: ['waves', 'ocean', 'water'] },
  { name: 'Tsunami', provider: 'material', class: 'Tsunami', keywords: ['tsunami', 'wave', 'water'] },
  { name: 'Air', provider: 'material', class: 'Air', keywords: ['air', 'wind', 'breeze'] },
  { name: 'Thunderstorm', provider: 'material', class: 'Thunderstorm', keywords: ['storm', 'thunder', 'weather'] },
  { name: 'Cloud', provider: 'material', class: 'Cloud', keywords: ['cloud', 'weather', 'sky'] },
  { name: 'Sunny', provider: 'material', class: 'WbSunny', keywords: ['sunny', 'sun', 'weather', 'bright'] },
  { name: 'Nightlight', provider: 'material', class: 'Nightlight', keywords: ['night', 'moon', 'dark'] },
  { name: 'Nights Stay', provider: 'material', class: 'NightsStay', keywords: ['night', 'moon', 'stars'] },
  { name: 'Flare', provider: 'material', class: 'Flare', keywords: ['sun', 'flare', 'light'] },

  // ===== TRAVEL & TRANSPORT =====
  { name: 'Flight', provider: 'material', class: 'Flight', keywords: ['flight', 'plane', 'travel', 'airport'] },
  { name: 'Flight Takeoff', provider: 'material', class: 'FlightTakeoff', keywords: ['flight', 'takeoff', 'plane'] },
  { name: 'Flight Land', provider: 'material', class: 'FlightLand', keywords: ['flight', 'land', 'plane'] },
  { name: 'Local Airport', provider: 'material', class: 'LocalAirport', keywords: ['airport', 'plane', 'travel'] },
  { name: 'Luggage', provider: 'material', class: 'Luggage', keywords: ['luggage', 'travel', 'bag'] },
  { name: 'Directions Car', provider: 'material', class: 'DirectionsCar', keywords: ['car', 'drive', 'transport'] },
  { name: 'Car Rental', provider: 'material', class: 'CarRental', keywords: ['car', 'rental', 'key'] },
  { name: 'Local Taxi', provider: 'material', class: 'LocalTaxi', keywords: ['taxi', 'cab', 'transport'] },
  { name: 'Directions Bus', provider: 'material', class: 'DirectionsBus', keywords: ['bus', 'transport', 'public'] },
  { name: 'Train', provider: 'material', class: 'Train', keywords: ['train', 'transport', 'rail'] },
  { name: 'Subway', provider: 'material', class: 'Subway', keywords: ['subway', 'metro', 'transport'] },
  { name: 'Tram', provider: 'material', class: 'Tram', keywords: ['tram', 'transport', 'rail'] },
  { name: 'Directions Boat', provider: 'material', class: 'DirectionsBoat', keywords: ['boat', 'ship', 'water'] },
  { name: 'Sailing', provider: 'material', class: 'Sailing', keywords: ['sailing', 'boat', 'water'] },
  { name: 'Two Wheeler', provider: 'material', class: 'TwoWheeler', keywords: ['motorcycle', 'bike', 'scooter'] },
  { name: 'Electric Scooter', provider: 'material', class: 'ElectricScooter', keywords: ['scooter', 'electric', 'transport'] },
  { name: 'Pedal Bike', provider: 'material', class: 'PedalBike', keywords: ['bike', 'bicycle', 'cycling'] },
  { name: 'Electric Bike', provider: 'material', class: 'ElectricBike', keywords: ['bike', 'electric', 'cycling'] },
  { name: 'Explore', provider: 'material', class: 'Explore', keywords: ['explore', 'compass', 'travel'] },
  { name: 'Map', provider: 'material', class: 'Map', keywords: ['map', 'navigation', 'location'] },
  { name: 'Place', provider: 'material', class: 'Place', keywords: ['place', 'location', 'pin'] },
  { name: 'Location On', provider: 'material', class: 'LocationOn', keywords: ['location', 'pin', 'map'] },
  { name: 'My Location', provider: 'material', class: 'MyLocation', keywords: ['location', 'gps', 'here'] },
  { name: 'Near Me', provider: 'material', class: 'NearMe', keywords: ['near', 'location', 'arrow'] },
  { name: 'Navigation', provider: 'material', class: 'Navigation', keywords: ['navigation', 'arrow', 'direction'] },
  { name: 'Directions', provider: 'material', class: 'Directions', keywords: ['directions', 'route', 'path'] },
  { name: 'Route', provider: 'material', class: 'Route', keywords: ['route', 'path', 'directions'] },
  { name: 'Trip Origin', provider: 'material', class: 'TripOrigin', keywords: ['trip', 'origin', 'start'] },
  { name: 'Beenhere', provider: 'material', class: 'Beenhere', keywords: ['been here', 'visited', 'check'] },

  // ===== SETTINGS & TOOLS =====
  { name: 'Settings', provider: 'material', class: 'Settings', keywords: ['settings', 'config', 'gear', 'preferences'] },
  { name: 'Settings Applications', provider: 'material', class: 'SettingsApplications', keywords: ['settings', 'app', 'config'] },
  { name: 'Tune', provider: 'material', class: 'Tune', keywords: ['tune', 'adjust', 'settings'] },
  { name: 'Toggle On', provider: 'material', class: 'ToggleOn', keywords: ['toggle', 'on', 'switch'] },
  { name: 'Toggle Off', provider: 'material', class: 'ToggleOff', keywords: ['toggle', 'off', 'switch'] },
  { name: 'Admin Panel Settings', provider: 'material', class: 'AdminPanelSettings', keywords: ['admin', 'settings', 'panel'] },
  { name: 'Manage Accounts', provider: 'material', class: 'ManageAccounts', keywords: ['manage', 'account', 'user'] },
  { name: 'Account Circle', provider: 'material', class: 'AccountCircle', keywords: ['account', 'user', 'profile'] },
  { name: 'Privacy Tip', provider: 'material', class: 'PrivacyTip', keywords: ['privacy', 'shield', 'security'] },
  { name: 'Security', provider: 'material', class: 'Security', keywords: ['security', 'shield', 'safe'] },
  { name: 'Lock', provider: 'material', class: 'Lock', keywords: ['lock', 'secure', 'password'] },
  { name: 'Lock Open', provider: 'material', class: 'LockOpen', keywords: ['lock', 'open', 'unlock'] },
  { name: 'Key', provider: 'material', class: 'Key', keywords: ['key', 'password', 'access'] },
  { name: 'VPN Key', provider: 'material', class: 'VpnKey', keywords: ['key', 'vpn', 'security'] },
  { name: 'Password', provider: 'material', class: 'Password', keywords: ['password', 'key', 'security'] },

  // ===== UI & ACTIONS =====
  { name: 'Add', provider: 'material', class: 'Add', keywords: ['add', 'plus', 'new', 'create'] },
  { name: 'Add Circle', provider: 'material', class: 'AddCircle', keywords: ['add', 'plus', 'circle'] },
  { name: 'Remove', provider: 'material', class: 'Remove', keywords: ['remove', 'minus', 'delete'] },
  { name: 'Remove Circle', provider: 'material', class: 'RemoveCircle', keywords: ['remove', 'minus', 'circle'] },
  { name: 'Delete', provider: 'material', class: 'Delete', keywords: ['delete', 'trash', 'remove'] },
  { name: 'Delete Forever', provider: 'material', class: 'DeleteForever', keywords: ['delete', 'forever', 'permanent'] },
  { name: 'Close', provider: 'material', class: 'Close', keywords: ['close', 'x', 'cancel'] },
  { name: 'Cancel', provider: 'material', class: 'Cancel', keywords: ['cancel', 'x', 'close'] },
  { name: 'Block', provider: 'material', class: 'Block', keywords: ['block', 'stop', 'no'] },
  { name: 'Do Not Disturb', provider: 'material', class: 'DoNotDisturb', keywords: ['do not disturb', 'dnd', 'no'] },
  { name: 'Save', provider: 'material', class: 'Save', keywords: ['save', 'disk', 'floppy'] },
  { name: 'Save Alt', provider: 'material', class: 'SaveAlt', keywords: ['save', 'download', 'export'] },
  { name: 'Download', provider: 'material', class: 'Download', keywords: ['download', 'save', 'arrow'] },
  { name: 'Upload', provider: 'material', class: 'Upload', keywords: ['upload', 'arrow', 'send'] },
  { name: 'Publish', provider: 'material', class: 'Publish', keywords: ['publish', 'upload', 'arrow'] },
  { name: 'Share', provider: 'material', class: 'Share', keywords: ['share', 'social', 'send'] },
  { name: 'IOS Share', provider: 'material', class: 'IosShare', keywords: ['share', 'ios', 'export'] },
  { name: 'Copy', provider: 'material', class: 'ContentCopy', keywords: ['copy', 'duplicate', 'clone'] },
  { name: 'Paste', provider: 'material', class: 'ContentPaste', keywords: ['paste', 'clipboard'] },
  { name: 'Cut', provider: 'material', class: 'ContentCut', keywords: ['cut', 'scissors'] },
  { name: 'Undo', provider: 'material', class: 'Undo', keywords: ['undo', 'back', 'arrow'] },
  { name: 'Redo', provider: 'material', class: 'Redo', keywords: ['redo', 'forward', 'arrow'] },
  { name: 'Refresh', provider: 'material', class: 'Refresh', keywords: ['refresh', 'reload', 'sync'] },
  { name: 'Sync', provider: 'material', class: 'Sync', keywords: ['sync', 'refresh', 'update'] },
  { name: 'Autorenew', provider: 'material', class: 'Autorenew', keywords: ['autorenew', 'refresh', 'sync'] },
  { name: 'Search', provider: 'material', class: 'Search', keywords: ['search', 'find', 'magnify'] },
  { name: 'Zoom In', provider: 'material', class: 'ZoomIn', keywords: ['zoom', 'in', 'magnify'] },
  { name: 'Zoom Out', provider: 'material', class: 'ZoomOut', keywords: ['zoom', 'out', 'magnify'] },
  { name: 'Filter', provider: 'material', class: 'FilterList', keywords: ['filter', 'list', 'sort'] },
  { name: 'Sort', provider: 'material', class: 'Sort', keywords: ['sort', 'order', 'arrange'] },
  { name: 'Expand More', provider: 'material', class: 'ExpandMore', keywords: ['expand', 'more', 'down'] },
  { name: 'Expand Less', provider: 'material', class: 'ExpandLess', keywords: ['expand', 'less', 'up'] },
  { name: 'Chevron Right', provider: 'material', class: 'ChevronRight', keywords: ['chevron', 'right', 'arrow'] },
  { name: 'Chevron Left', provider: 'material', class: 'ChevronLeft', keywords: ['chevron', 'left', 'arrow'] },
  { name: 'Arrow Forward', provider: 'material', class: 'ArrowForward', keywords: ['arrow', 'forward', 'next'] },
  { name: 'Arrow Back', provider: 'material', class: 'ArrowBack', keywords: ['arrow', 'back', 'previous'] },
  { name: 'Arrow Upward', provider: 'material', class: 'ArrowUpward', keywords: ['arrow', 'up', 'top'] },
  { name: 'Arrow Downward', provider: 'material', class: 'ArrowDownward', keywords: ['arrow', 'down', 'bottom'] },
  { name: 'Menu', provider: 'material', class: 'Menu', keywords: ['menu', 'hamburger', 'nav'] },
  { name: 'More Vert', provider: 'material', class: 'MoreVert', keywords: ['more', 'vertical', 'options'] },
  { name: 'More Horiz', provider: 'material', class: 'MoreHoriz', keywords: ['more', 'horizontal', 'options'] },
  { name: 'Apps', provider: 'material', class: 'Apps', keywords: ['apps', 'grid', 'menu'] },
  { name: 'Dashboard', provider: 'material', class: 'Dashboard', keywords: ['dashboard', 'home', 'grid'] },
  { name: 'Widgets', provider: 'material', class: 'Widgets', keywords: ['widgets', 'blocks', 'components'] },
  { name: 'View Module', provider: 'material', class: 'ViewModule', keywords: ['view', 'module', 'grid'] },
  { name: 'View List', provider: 'material', class: 'ViewList', keywords: ['view', 'list', 'rows'] },
  { name: 'View Kanban', provider: 'material', class: 'ViewKanban', keywords: ['kanban', 'board', 'columns'] },

  // ===== FILES & FOLDERS =====
  { name: 'Folder', provider: 'material', class: 'Folder', keywords: ['folder', 'directory', 'files'] },
  { name: 'Folder Open', provider: 'material', class: 'FolderOpen', keywords: ['folder', 'open', 'directory'] },
  { name: 'Folder Special', provider: 'material', class: 'FolderSpecial', keywords: ['folder', 'special', 'star'] },
  { name: 'Create New Folder', provider: 'material', class: 'CreateNewFolder', keywords: ['folder', 'new', 'create'] },
  { name: 'Folder Shared', provider: 'material', class: 'FolderShared', keywords: ['folder', 'shared', 'team'] },
  { name: 'Insert Drive File', provider: 'material', class: 'InsertDriveFile', keywords: ['file', 'document', 'drive'] },
  { name: 'File Present', provider: 'material', class: 'FilePresent', keywords: ['file', 'present', 'check'] },
  { name: 'File Copy', provider: 'material', class: 'FileCopy', keywords: ['file', 'copy', 'duplicate'] },
  { name: 'Attachment', provider: 'material', class: 'Attachment', keywords: ['attachment', 'clip', 'file'] },
  { name: 'Link', provider: 'material', class: 'Link', keywords: ['link', 'chain', 'url'] },
  { name: 'Link Off', provider: 'material', class: 'LinkOff', keywords: ['link', 'off', 'unlink'] },
  { name: 'Image', provider: 'material', class: 'Image', keywords: ['image', 'photo', 'picture'] },
  { name: 'Photo', provider: 'material', class: 'Photo', keywords: ['photo', 'image', 'picture'] },
  { name: 'Collections', provider: 'material', class: 'Collections', keywords: ['collections', 'photos', 'album'] },
  { name: 'Photo Library', provider: 'material', class: 'PhotoLibrary', keywords: ['photo', 'library', 'album'] },
  { name: 'Video Library', provider: 'material', class: 'VideoLibrary', keywords: ['video', 'library', 'collection'] },
  { name: 'Inventory', provider: 'material', class: 'Inventory', keywords: ['inventory', 'box', 'stock'] },
  { name: 'Archive', provider: 'material', class: 'Archive', keywords: ['archive', 'box', 'storage'] },
  { name: 'Unarchive', provider: 'material', class: 'Unarchive', keywords: ['unarchive', 'box', 'restore'] },

  // ===== MISC & FUN =====
  { name: 'Bolt', provider: 'material', class: 'Bolt', keywords: ['bolt', 'energy', 'fast', 'lightning', 'power'] },
  { name: 'Electric Bolt', provider: 'material', class: 'ElectricBolt', keywords: ['electric', 'bolt', 'energy'] },
  { name: 'Rocket Launch', provider: 'material', class: 'RocketLaunch', keywords: ['rocket', 'launch', 'fast', 'startup'] },
  { name: 'Rocket', provider: 'material', class: 'Rocket', keywords: ['rocket', 'space', 'launch'] },
  { name: 'Volunteer Activism', provider: 'material', class: 'VolunteerActivism', keywords: ['volunteer', 'help', 'charity', 'heart', 'hand'] },
  { name: 'Celebration', provider: 'material', class: 'Celebration', keywords: ['celebrate', 'party', 'fun', 'confetti'] },
  { name: 'Cake', provider: 'material', class: 'Cake', keywords: ['cake', 'birthday', 'celebration'] },
  { name: 'Local Fire Department', provider: 'material', class: 'LocalFireDepartment', keywords: ['fire', 'flame', 'hot'] },
  { name: 'Whatshot', provider: 'material', class: 'Whatshot', keywords: ['hot', 'fire', 'trending', 'flame'] },
  { name: 'Diamond', provider: 'material', class: 'Diamond', keywords: ['diamond', 'gem', 'valuable'] },
  { name: 'Token', provider: 'material', class: 'Token', keywords: ['token', 'coin', 'crypto'] },
  { name: 'Toll', provider: 'material', class: 'Toll', keywords: ['toll', 'coins', 'payment'] },
  { name: 'Casino', provider: 'material', class: 'Casino', keywords: ['casino', 'dice', 'game', 'luck'] },
  { name: 'Extension', provider: 'material', class: 'Extension', keywords: ['puzzle', 'extension', 'plugin'] },
  { name: 'Emoji Objects', provider: 'material', class: 'EmojiObjects', keywords: ['lightbulb', 'idea', 'emoji'] },
  { name: 'Emoji Nature', provider: 'material', class: 'EmojiNature', keywords: ['nature', 'bee', 'emoji'] },
  { name: 'Emoji Food', provider: 'material', class: 'EmojiFoodBeverage', keywords: ['food', 'coffee', 'emoji'] },
  { name: 'Emoji Transportation', provider: 'material', class: 'EmojiTransportation', keywords: ['car', 'transport', 'emoji'] },
  { name: 'Emoji Symbols', provider: 'material', class: 'EmojiSymbols', keywords: ['symbols', 'music', 'emoji'] },
  { name: 'Fingerprint', provider: 'material', class: 'Fingerprint', keywords: ['fingerprint', 'identity', 'security'] },
  { name: 'QR Code', provider: 'material', class: 'QrCode', keywords: ['qr', 'code', 'scan'] },
  { name: 'Tag', provider: 'material', class: 'Tag', keywords: ['tag', 'label', 'price'] },
  { name: 'Straighten', provider: 'material', class: 'Straighten', keywords: ['ruler', 'measure', 'straight'] },
  { name: 'Speed', provider: 'material', class: 'Speed', keywords: ['speed', 'fast', 'gauge'] },
  { name: 'Offline Bolt', provider: 'material', class: 'OfflineBolt', keywords: ['offline', 'bolt', 'flash'] },
  { name: 'Power', provider: 'material', class: 'Power', keywords: ['power', 'plug', 'electric'] },
  { name: 'Power Off', provider: 'material', class: 'PowerOff', keywords: ['power', 'off', 'shutdown'] },
  { name: 'Battery Full', provider: 'material', class: 'BatteryFull', keywords: ['battery', 'full', 'power'] },
  { name: 'Battery Charging', provider: 'material', class: 'BatteryChargingFull', keywords: ['battery', 'charging', 'power'] },
  { name: 'Brightness High', provider: 'material', class: 'BrightnessHigh', keywords: ['brightness', 'sun', 'light'] },
  { name: 'Brightness Low', provider: 'material', class: 'BrightnessLow', keywords: ['brightness', 'dim', 'dark'] },
  { name: 'Light Mode', provider: 'material', class: 'LightMode', keywords: ['light', 'sun', 'day'] },
  { name: 'Dark Mode', provider: 'material', class: 'DarkMode', keywords: ['dark', 'moon', 'night'] },
  { name: 'Contrast', provider: 'material', class: 'Contrast', keywords: ['contrast', 'circle', 'adjust'] },

  // ===== SPIRITUAL & MINDFULNESS =====
  { name: 'Church', provider: 'material', class: 'Church', keywords: ['church', 'religion', 'spiritual'] },
  { name: 'Temple Hindu', provider: 'material', class: 'TempleHindu', keywords: ['temple', 'hindu', 'spiritual'] },
  { name: 'Temple Buddhist', provider: 'material', class: 'TempleBuddhist', keywords: ['temple', 'buddhist', 'spiritual'] },
  { name: 'Mosque', provider: 'material', class: 'Mosque', keywords: ['mosque', 'islam', 'spiritual'] },
  { name: 'Synagogue', provider: 'material', class: 'Synagogue', keywords: ['synagogue', 'jewish', 'spiritual'] },

  // ===== HELP & INFO =====
  { name: 'Help', provider: 'material', class: 'Help', keywords: ['help', 'question', 'support'] },
  { name: 'Help Outline', provider: 'material', class: 'HelpOutline', keywords: ['help', 'question', 'outline'] },
  { name: 'Info', provider: 'material', class: 'Info', keywords: ['info', 'information', 'about'] },
  { name: 'Info Outline', provider: 'material', class: 'InfoOutlined', keywords: ['info', 'outline', 'about'] },
  { name: 'Warning', provider: 'material', class: 'Warning', keywords: ['warning', 'alert', 'caution'] },
  { name: 'Warning Amber', provider: 'material', class: 'WarningAmber', keywords: ['warning', 'amber', 'alert'] },
  { name: 'Error', provider: 'material', class: 'Error', keywords: ['error', 'alert', 'problem'] },
  { name: 'Error Outline', provider: 'material', class: 'ErrorOutline', keywords: ['error', 'outline', 'alert'] },
  { name: 'Priority High', provider: 'material', class: 'PriorityHigh', keywords: ['priority', 'high', 'important'] },
  { name: 'Report', provider: 'material', class: 'Report', keywords: ['report', 'alert', 'warning'] },
  { name: 'Report Problem', provider: 'material', class: 'ReportProblem', keywords: ['report', 'problem', 'warning'] },
  { name: 'New Releases', provider: 'material', class: 'NewReleases', keywords: ['new', 'releases', 'alert'] },
  { name: 'Highlight Off', provider: 'material', class: 'HighlightOff', keywords: ['highlight', 'off', 'cancel'] },
];

// Font Awesome icons - Additional icons for variety
export const FONTAWESOME_ICONS: IconDefinition[] = [
  // Health & Fitness
  { name: 'Dumbbell', provider: 'fontawesome', class: 'fa-solid fa-dumbbell', keywords: ['gym', 'fitness', 'exercise', 'workout'] },
  { name: 'Heart Pulse', provider: 'fontawesome', class: 'fa-solid fa-heart-pulse', keywords: ['health', 'heartbeat', 'cardio'] },
  { name: 'Running', provider: 'fontawesome', class: 'fa-solid fa-person-running', keywords: ['running', 'exercise', 'cardio', 'jog'] },
  { name: 'Walking', provider: 'fontawesome', class: 'fa-solid fa-person-walking', keywords: ['walking', 'exercise', 'steps'] },
  { name: 'Biking', provider: 'fontawesome', class: 'fa-solid fa-person-biking', keywords: ['biking', 'cycling', 'exercise'] },
  { name: 'Swimming', provider: 'fontawesome', class: 'fa-solid fa-person-swimming', keywords: ['swimming', 'pool', 'exercise'] },
  { name: 'Yoga', provider: 'fontawesome', class: 'fa-solid fa-spa', keywords: ['meditation', 'spa', 'relax', 'yoga'] },

  // Mind & Mental
  { name: 'Brain', provider: 'fontawesome', class: 'fa-solid fa-brain', keywords: ['brain', 'think', 'mental', 'mind'] },
  { name: 'Heart', provider: 'fontawesome', class: 'fa-solid fa-heart', keywords: ['heart', 'love', 'health', 'wellness'] },
  { name: 'Face Smile', provider: 'fontawesome', class: 'fa-solid fa-face-smile', keywords: ['smile', 'happy', 'mood', 'emotion'] },
  { name: 'Comments', provider: 'fontawesome', class: 'fa-solid fa-comments', keywords: ['chat', 'talk', 'social', 'communication'] },

  // Achievement & Gaming
  { name: 'Trophy', provider: 'fontawesome', class: 'fa-solid fa-trophy', keywords: ['trophy', 'win', 'achievement', 'award'] },
  { name: 'Medal', provider: 'fontawesome', class: 'fa-solid fa-medal', keywords: ['medal', 'achievement', 'award'] },
  { name: 'Crown', provider: 'fontawesome', class: 'fa-solid fa-crown', keywords: ['crown', 'king', 'winner', 'best'] },
  { name: 'Fire', provider: 'fontawesome', class: 'fa-solid fa-fire', keywords: ['fire', 'streak', 'hot', 'burning'] },
  { name: 'Bolt', provider: 'fontawesome', class: 'fa-solid fa-bolt', keywords: ['bolt', 'energy', 'power', 'lightning'] },
  { name: 'Gem', provider: 'fontawesome', class: 'fa-solid fa-gem', keywords: ['gem', 'diamond', 'valuable', 'reward'] },
  { name: 'Star', provider: 'fontawesome', class: 'fa-solid fa-star', keywords: ['star', 'favorite', 'rating'] },
  { name: 'Dice', provider: 'fontawesome', class: 'fa-solid fa-dice', keywords: ['dice', 'game', 'random', 'play'] },
  { name: 'Gamepad', provider: 'fontawesome', class: 'fa-solid fa-gamepad', keywords: ['game', 'gaming', 'play', 'controller'] },
  { name: 'Puzzle', provider: 'fontawesome', class: 'fa-solid fa-puzzle-piece', keywords: ['puzzle', 'game', 'solve'] },

  // Time & Planning
  { name: 'Clock', provider: 'fontawesome', class: 'fa-solid fa-clock', keywords: ['clock', 'time', 'schedule'] },
  { name: 'Hourglass', provider: 'fontawesome', class: 'fa-solid fa-hourglass-half', keywords: ['hourglass', 'time', 'wait'] },
  { name: 'Calendar Days', provider: 'fontawesome', class: 'fa-solid fa-calendar-days', keywords: ['calendar', 'date', 'schedule'] },
  { name: 'Calendar Check', provider: 'fontawesome', class: 'fa-solid fa-calendar-check', keywords: ['calendar', 'done', 'scheduled'] },
  { name: 'Bell', provider: 'fontawesome', class: 'fa-solid fa-bell', keywords: ['bell', 'notification', 'reminder'] },

  // Productivity & Work
  { name: 'Rocket', provider: 'fontawesome', class: 'fa-solid fa-rocket', keywords: ['rocket', 'launch', 'fast', 'startup'] },
  { name: 'Bullseye', provider: 'fontawesome', class: 'fa-solid fa-bullseye', keywords: ['target', 'goal', 'aim', 'focus'] },
  { name: 'Crosshairs', provider: 'fontawesome', class: 'fa-solid fa-crosshairs', keywords: ['focus', 'target', 'aim'] },
  { name: 'Check', provider: 'fontawesome', class: 'fa-solid fa-check', keywords: ['check', 'done', 'complete'] },
  { name: 'Check Double', provider: 'fontawesome', class: 'fa-solid fa-check-double', keywords: ['check', 'done', 'verified'] },
  { name: 'List Check', provider: 'fontawesome', class: 'fa-solid fa-list-check', keywords: ['list', 'tasks', 'todo', 'checklist'] },
  { name: 'Clipboard', provider: 'fontawesome', class: 'fa-solid fa-clipboard-list', keywords: ['clipboard', 'list', 'tasks'] },
  { name: 'Folder', provider: 'fontawesome', class: 'fa-solid fa-folder', keywords: ['folder', 'project', 'organize'] },
  { name: 'Laptop', provider: 'fontawesome', class: 'fa-solid fa-laptop-code', keywords: ['laptop', 'code', 'programming'] },
  { name: 'Briefcase', provider: 'fontawesome', class: 'fa-solid fa-briefcase', keywords: ['work', 'business', 'job'] },

  // Food & Drink
  { name: 'Coffee', provider: 'fontawesome', class: 'fa-solid fa-mug-hot', keywords: ['coffee', 'drink', 'morning', 'hot'] },
  { name: 'Apple', provider: 'fontawesome', class: 'fa-solid fa-apple-whole', keywords: ['apple', 'fruit', 'healthy'] },
  { name: 'Utensils', provider: 'fontawesome', class: 'fa-solid fa-utensils', keywords: ['food', 'eat', 'dining'] },
  { name: 'Glass Water', provider: 'fontawesome', class: 'fa-solid fa-glass-water', keywords: ['water', 'drink', 'hydration'] },
  { name: 'Bottle Water', provider: 'fontawesome', class: 'fa-solid fa-bottle-water', keywords: ['water', 'drink', 'hydration'] },
  { name: 'Carrot', provider: 'fontawesome', class: 'fa-solid fa-carrot', keywords: ['carrot', 'vegetable', 'healthy'] },

  // Rest & Sleep
  { name: 'Bed', provider: 'fontawesome', class: 'fa-solid fa-bed', keywords: ['bed', 'sleep', 'rest', 'night'] },
  { name: 'Moon', provider: 'fontawesome', class: 'fa-solid fa-moon', keywords: ['moon', 'night', 'sleep'] },
  { name: 'Sun', provider: 'fontawesome', class: 'fa-solid fa-sun', keywords: ['sun', 'morning', 'day', 'bright'] },
  { name: 'Couch', provider: 'fontawesome', class: 'fa-solid fa-couch', keywords: ['couch', 'relax', 'rest'] },

  // Learning
  { name: 'Book', provider: 'fontawesome', class: 'fa-solid fa-book', keywords: ['book', 'read', 'study', 'learn'] },
  { name: 'Book Open', provider: 'fontawesome', class: 'fa-solid fa-book-open', keywords: ['book', 'read', 'study'] },
  { name: 'Graduation Cap', provider: 'fontawesome', class: 'fa-solid fa-graduation-cap', keywords: ['graduation', 'education', 'school'] },
  { name: 'Pen', provider: 'fontawesome', class: 'fa-solid fa-pen', keywords: ['pen', 'write', 'journal'] },
  { name: 'Pencil', provider: 'fontawesome', class: 'fa-solid fa-pencil', keywords: ['pencil', 'write', 'draw'] },
  { name: 'Language', provider: 'fontawesome', class: 'fa-solid fa-language', keywords: ['language', 'learn', 'translate'] },

  // Finance
  { name: 'Dollar', provider: 'fontawesome', class: 'fa-solid fa-dollar-sign', keywords: ['dollar', 'money', 'finance'] },
  { name: 'Piggy Bank', provider: 'fontawesome', class: 'fa-solid fa-piggy-bank', keywords: ['savings', 'money', 'bank'] },
  { name: 'Wallet', provider: 'fontawesome', class: 'fa-solid fa-wallet', keywords: ['wallet', 'money', 'payment'] },
  { name: 'Chart Line', provider: 'fontawesome', class: 'fa-solid fa-chart-line', keywords: ['chart', 'graph', 'growth', 'progress'] },

  // Misc
  { name: 'Guitar', provider: 'fontawesome', class: 'fa-solid fa-guitar', keywords: ['guitar', 'music', 'instrument'] },
  { name: 'Headphones', provider: 'fontawesome', class: 'fa-solid fa-headphones', keywords: ['headphones', 'music', 'audio'] },
  { name: 'Camera', provider: 'fontawesome', class: 'fa-solid fa-camera', keywords: ['camera', 'photo', 'picture'] },
  { name: 'Paintbrush', provider: 'fontawesome', class: 'fa-solid fa-paintbrush', keywords: ['paint', 'art', 'creative'] },
  { name: 'Seedling', provider: 'fontawesome', class: 'fa-solid fa-seedling', keywords: ['plant', 'grow', 'nature', 'garden'] },
  { name: 'Leaf', provider: 'fontawesome', class: 'fa-solid fa-leaf', keywords: ['leaf', 'nature', 'eco', 'green'] },
  { name: 'Tree', provider: 'fontawesome', class: 'fa-solid fa-tree', keywords: ['tree', 'nature', 'environment'] },
  { name: 'Mountain', provider: 'fontawesome', class: 'fa-solid fa-mountain', keywords: ['mountain', 'hiking', 'outdoor'] },
  { name: 'Dog', provider: 'fontawesome', class: 'fa-solid fa-dog', keywords: ['dog', 'pet', 'animal'] },
  { name: 'Cat', provider: 'fontawesome', class: 'fa-solid fa-cat', keywords: ['cat', 'pet', 'animal'] },
  { name: 'Broom', provider: 'fontawesome', class: 'fa-solid fa-broom', keywords: ['clean', 'broom', 'tidy'] },
  { name: 'House', provider: 'fontawesome', class: 'fa-solid fa-house', keywords: ['house', 'home', 'living'] },
  { name: 'Car', provider: 'fontawesome', class: 'fa-solid fa-car', keywords: ['car', 'drive', 'commute'] },
  { name: 'Plane', provider: 'fontawesome', class: 'fa-solid fa-plane', keywords: ['plane', 'travel', 'flight'] },
  { name: 'Hands Praying', provider: 'fontawesome', class: 'fa-solid fa-hands-praying', keywords: ['pray', 'spiritual', 'meditation'] },
  { name: 'Cross', provider: 'fontawesome', class: 'fa-solid fa-cross', keywords: ['cross', 'spiritual', 'faith'] },
  { name: 'Yin Yang', provider: 'fontawesome', class: 'fa-solid fa-yin-yang', keywords: ['balance', 'zen', 'harmony'] },
  { name: 'Infinity', provider: 'fontawesome', class: 'fa-solid fa-infinity', keywords: ['infinity', 'forever', 'endless'] },
];

// All icons combined
export const ALL_ICONS = [...MATERIAL_ICONS, ...FONTAWESOME_ICONS];

// Color palette for icons - curated for habit tracking
export const ICON_COLORS = [
  '#ef4444', // red - urgency, health
  '#f97316', // orange - energy, creativity
  '#fbbf24', // amber - attention, warning
  '#84cc16', // lime - growth, fresh
  '#22c55e', // green - success, health
  '#14b8a6', // teal - balance, calm (default)
  '#06b6d4', // cyan - clarity, focus
  '#3b82f6', // blue - trust, productivity
  '#6366f1', // indigo - wisdom, depth
  '#8b5cf6', // violet - creativity, luxury
  '#a855f7', // purple - imagination, spiritual
  '#ec4899', // pink - love, care
  '#f43f5e', // rose - passion, romance
  '#6b7280', // gray - neutral, professional
  '#ffffff', // white - clean, minimal
];

// Default color for new icons
export const DEFAULT_ICON_COLOR = '#14b8a6'; // teal
